### ISSUE TITLE
DSG-neu

### ISSUE THREAD

**Issue by petarmarj** [DigitaleGesellschaft/Datenauskunftsbegehren-Data#23]
Bevor es zwischen Tisch und Angel
fällt: Hat jemand schon die Texte an DSG-neu angepasst und hat diese in Pipeline?

Ich hätte sonst ein wenig Ressourcen, das heute anzuschauen, um die YML- und andere Files zu überfliegen. Gerne mit entsprechendem Merge-Segen einer juristischen Fachperson.

**Comment by petarmarj** [comment]
Habe mir sagen lassen, dass da schon was in Arbeit ist. Freue mich!

**Comment by nielsson4711** [comment]
Nützlich aber nicht dringend wäre eine Analyse bestimmter YML-Files.
Hinweise siehe: Abschnitt "Angaben .." unter https://github.com/nielsson4711/Datenauskunftsbegehren-Data/blob/R2023.09p1/README.md
(pullrequest pending)

Liste siehe: https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren-Data/pull/24/commits/b6a568f7dca4583f64344f26ee4340fa9a376120#diff-cf6e3dbba196e495273cf1f0ba81c927bbeb7e842e201641189ac469202dbcf7
