### ISSUE TITLE
YAML Schema validieren

### ISSUE THREAD

**Issue by ideadapt** [DigitaleGesellschaft/Datenauskunftsbegehren-Data#9]
z.B. via eines JSON Schema ist das mit https://json-schema-everywhere.github.io/yaml möglich.

Vorteil: Ungültige Keys oder ungültige Formate der Values werden erkannt. Allenfalls könnte man sogar noch custom validation rules hinzufügen um die Variabel Syntax zu prüfen.

**Comment by nielsson4711** [comment]
Wurde offenbar zwischenzeitlich implementiert, siehe bspw https://github.com/DigitaleGesellschaft/Datenauskunftsbegehren-Data/actions/runs/12254884296/job/34186764912?pr=32
